version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - data:/data
volumes:
  data:
networks:
  node-red-net:
